/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Korisnik;
import domen.Narudzbina;
import interfejsi.DomenskiObjekat;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import kom.KomunikacijaSaServerom;
import konstante.Operacije;
import logika.KontrolerKlijent;
import modeli.ModelTabeleNarudzbina;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Iva
 */
public class NarudzbineForma extends javax.swing.JFrame {

    private static ResourceBundle bundle_sr_RS;
    Korisnik ulog;
    /**
     * Creates new form NarudzbineForma
     */
    public NarudzbineForma(Korisnik ulog, ResourceBundle bundle) {
        bundle_sr_RS = bundle;
        initComponents();
        setLocationRelativeTo(null);
        
        postaviSliku();
        
        this.ulog = ulog;
        
        KontrolerKlijent.getInstanca().setNf(this);
        
        tabelaNar.setModel(new ModelTabeleNarudzbina(bundle_sr_RS));
        try {
            popuniTabelu();
        } catch (Exception ex) {
            Logger.getLogger(NarudzbineForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                KontrolerKlijent.getInstanca().posaljiZahtevZaGasenjeKorisnika();
                dispose();
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPretrazi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaNar = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        btnObradi = new javax.swing.JButton();
        btnStorniraj = new javax.swing.JButton();
        lblJezik = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(bundle_sr_RS.getString("PRETRAŽI:")); // NOI18N

        txtPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPretraziActionPerformed(evt);
            }
        });
        txtPretrazi.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtPretraziPropertyChange(evt);
            }
        });

        tabelaNar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaNar);

        btnDodaj.setText(bundle_sr_RS.getString("DODAJ NARUDŽBINU")); // NOI18N
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObradi.setText(bundle_sr_RS.getString("OBRADI NARUDŽBINU")); // NOI18N
        btnObradi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObradiActionPerformed(evt);
            }
        });

        btnStorniraj.setText(bundle_sr_RS.getString("STORNIRAJ NARUDŽBINU")); // NOI18N
        btnStorniraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStornirajActionPerformed(evt);
            }
        });

        lblJezik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJezikMouseClicked(evt);
            }
        });

        jButton1.setText(bundle_sr_RS.getString("VRATI POCETNU"));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblJezik, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDodaj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnObradi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnStorniraj))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblJezik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnObradi)
                        .addComponent(btnStorniraj))
                    .addComponent(btnDodaj, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPretraziActionPerformed
        // TODO add your handling code here:
        String polje = txtPretrazi.getText();

        if (polje.isEmpty()) {
            try {
                popuniTabelu();
            } catch (Exception ex) {
                Logger.getLogger(NarudzbineForma.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            ModelTabeleNarudzbina mt = (ModelTabeleNarudzbina) tabelaNar.getModel();
            mt.pretrazi(polje);
        }

    }//GEN-LAST:event_txtPretraziActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        // TODO add your handling code here:
        UnesiNarudzbinu dn = new UnesiNarudzbinu(this, true, null, ulog, bundle_sr_RS);
        dn.setVisible(true);
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObradiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObradiActionPerformed
        // TODO add your handling code here:
        int red = tabelaNar.getSelectedRow();
        ModelTabeleNarudzbina mt = (ModelTabeleNarudzbina) tabelaNar.getModel();
        if (red != -1) {
            Narudzbina n = mt.vratiNaruzbinu(red);
            
            if (n.getStatus().equals("stornirano")) {
                JOptionPane.showMessageDialog(this, bundle_sr_RS.getString("OVA NARUDZBINA JE STORNIRANA"));
                return;
            }
            
            UnesiNarudzbinu un = new UnesiNarudzbinu(this, true, n, ulog, bundle_sr_RS);
            un.setVisible(true);
        }
    }//GEN-LAST:event_btnObradiActionPerformed

    private void btnStornirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStornirajActionPerformed
        // TODO add your handling code here:
        int red = tabelaNar.getSelectedRow();
        if (red != -1) {
            ModelTabeleNarudzbina mt = (ModelTabeleNarudzbina) tabelaNar.getModel();
            Narudzbina n = mt.vratiNaruzbinu(red);
            n.setStatus("stornirano");
            
            KontrolerKlijent.getInstanca().posaljiZahtevZaStorniranjeNarudzbine(n);
        }
    }//GEN-LAST:event_btnStornirajActionPerformed

    private void txtPretraziPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtPretraziPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPretraziPropertyChange

    private void lblJezikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJezikMouseClicked
        // TODO add your handling code here:
        if (bundle_sr_RS == ResourceBundle.getBundle("forme/Bundle_en")) {
            bundle_sr_RS = ResourceBundle.getBundle("forme/Bundle_sr_RS");
        } else {
            bundle_sr_RS = ResourceBundle.getBundle("forme/Bundle_en");
        }
        
        postaviSliku();
        
        btnStorniraj.setText(bundle_sr_RS.getString("STORNIRAJ NARUDŽBINU"));
        btnObradi.setText(bundle_sr_RS.getString("OBRADI NARUDŽBINU"));
        btnDodaj.setText(bundle_sr_RS.getString("DODAJ NARUDŽBINU"));
        jLabel1.setText(bundle_sr_RS.getString("PRETRAŽI:"));
        jButton1.setText(bundle_sr_RS.getString("VRATI POCETNU"));
        
//        tabelaNar.setModel(new ModelTabeleNarudzbina(bundle_sr_RS));
//        try {
//            popuniTabelu();
//        } catch (Exception ex) {
//            Logger.getLogger(NarudzbineForma.class.getName()).log(Level.SEVERE, null, ex);
//        }

        ModelTabeleNarudzbina mt = (ModelTabeleNarudzbina) tabelaNar.getModel();
        mt.setBundle_sr_RS(bundle_sr_RS);
        
    }//GEN-LAST:event_lblJezikMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new KlijentskaForma(ulog, bundle_sr_RS).setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObradi;
    private javax.swing.JButton btnStorniraj;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJezik;
    private javax.swing.JTable tabelaNar;
    private javax.swing.JTextField txtPretrazi;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() throws Exception {
        KontrolerKlijent.getInstanca().posaljiZahtevZaVracanjeNarudzbina();
    }
    
    public void osvezi() throws Exception{
        popuniTabelu();
    }

    public void stornirajNarudzbinu(ServerskiOdgovor so) {
        try {
            if (so.getIzuzetak() != null) {
                throw so.getIzuzetak();
            }
            
            Narudzbina n = (Narudzbina) so.getOdgovor();
            if (n != null) {
                JOptionPane.showMessageDialog(this, bundle_sr_RS.getString("USPESNO STORNIRANA"));
            } else {
                JOptionPane.showMessageDialog(this, bundle_sr_RS.getString("NEUSPESNO STORNIRANA"));
            }
            
            
//            JOptionPane.showMessageDialog(this, "Narudzbina je stornirana");
            popuniTabelu();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, bundle_sr_RS.getString("NEUSPESNO STORNIRANA") + "\n" + e.getMessage());
        }
    }

    public void postaviNarudzbine(ServerskiOdgovor so) {
        try {
            if (so.getIzuzetak() != null) {
                throw so.getIzuzetak();
            }

            ArrayList<DomenskiObjekat> narudzbine = (ArrayList<DomenskiObjekat>) so.getOdgovor();
            ModelTabeleNarudzbina mt = (ModelTabeleNarudzbina) tabelaNar.getModel();
            mt.setLista(narudzbine);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, bundle_sr_RS.getString("DOSLO JE DO GRESKE") + "\n" + e.getMessage());
        }
    }

    private void postaviSliku() {
        String jezik;
        
        if (bundle_sr_RS == ResourceBundle.getBundle("forme/Bundle_en")) {
            jezik = "/slike/srb.png";
        } else {
            jezik = "/slike/eng.png";
        }
        
        ImageIcon ikona = new javax.swing.ImageIcon(getClass().getResource(jezik));
        Image img = ikona.getImage() ;  
        Image newimg = img.getScaledInstance(lblJezik.getWidth(), lblJezik.getHeight(), Image.SCALE_SMOOTH);
        ikona = new ImageIcon( newimg );
        lblJezik.setIcon(ikona);
    }
    
    
}
