/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.Kupac;
import java.awt.Image;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logika.KontrolerKlijent;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Iva
 */
public class UnesiKupca extends javax.swing.JDialog {
    private Kupac nov;
    private static ResourceBundle bundle_sr_RS;
    /**
     * Creates new form UnesiKupca
     */
    public UnesiKupca(javax.swing.JDialog parent, boolean modal, ResourceBundle bundle_sr_RS) {
        super(parent, modal);
        this.bundle_sr_RS = bundle_sr_RS;
        initComponents();
        setLocationRelativeTo(null);
        
        postaviSliku();
        
        KontrolerKlijent.getInstanca().setuKupca(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAdresa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBrojFona = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblJezik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle_sr_RS.getString("UNESI KUPCA")));

        jLabel1.setText(bundle_sr_RS.getString("IME KUPCA:")); // NOI18N

        jLabel2.setText(bundle_sr_RS.getString("PREZIME KUPCA:")); // NOI18N

        jLabel3.setText(bundle_sr_RS.getString("ADRESA:")); // NOI18N

        jLabel4.setText(bundle_sr_RS.getString("BROJ TELEFONA:")); // NOI18N

        jLabel5.setText(bundle_sr_RS.getString("E-MAIL:")); // NOI18N

        jButton1.setText(bundle_sr_RS.getString("SAČUVAJ KUPCA")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIme))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAdresa, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBrojFona, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBrojFona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        lblJezik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJezikMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblJezik, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJezik, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ime = txtIme.getText();
        String prezime = txtPrezime.getText();
        String adresa = txtAdresa.getText();
        String brFona = txtBrojFona.getText();
        String email = txtEmail.getText();
        
        Kupac k = new Kupac(-1, ime, prezime, adresa, brFona, email);
        
        KontrolerKlijent.getInstanca().posaljiZahtevZaUnosKupca(k);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblJezikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJezikMouseClicked
        // TODO add your handling code here:
        if (bundle_sr_RS == ResourceBundle.getBundle("forme/Bundle_en")) {
            bundle_sr_RS = ResourceBundle.getBundle("forme/Bundle_sr_RS");
        } else {
            bundle_sr_RS = ResourceBundle.getBundle("forme/Bundle_en");
        }
        
        postaviSliku();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle_sr_RS.getString("UNESI KUPCA")));
        jLabel1.setText(bundle_sr_RS.getString("IME KUPCA:")); // NOI18N
        jLabel2.setText(bundle_sr_RS.getString("PREZIME KUPCA:")); // NOI18N
        jLabel3.setText(bundle_sr_RS.getString("ADRESA:")); // NOI18N
        jLabel4.setText(bundle_sr_RS.getString("BROJ TELEFONA:")); // NOI18N
        jLabel5.setText(bundle_sr_RS.getString("E-MAIL:")); // NOI18N
        jButton1.setText(bundle_sr_RS.getString("SAČUVAJ KUPCA"));
    }//GEN-LAST:event_lblJezikMouseClicked

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblJezik;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtBrojFona;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    public Kupac getNov() {
        return nov;
    }

    public void unesiKupca(ServerskiOdgovor so) {
        try {
            if (so.getIzuzetak() != null) {
                throw so.getIzuzetak();
            }
            
            Kupac kupac = (Kupac) so.getOdgovor();
            
            if (kupac.getKupacID() != -1) {
                JOptionPane.showMessageDialog(this, bundle_sr_RS.getString("USPESNO UNET KUPAC"));
                nov = kupac;
                
                if (this.getParent() != null) {
                    ((UnesiNarudzbinu) this.getParent()).postaviKupca(nov);
                }
                
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, bundle_sr_RS.getString("NIJE UNET KUPAC"));
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, bundle_sr_RS.getString("NIJE UNET KUPAC") + "\n"+ e.getMessage());
        }
    }

    private void postaviSliku() {
        String jezik;
        
        if (bundle_sr_RS == ResourceBundle.getBundle("forme/Bundle_en")) {
            jezik = "/slike/srb.png";
        } else {
            jezik = "/slike/eng.png";
        }
        
        ImageIcon ikona = new javax.swing.ImageIcon(getClass().getResource(jezik));
        Image img = ikona.getImage() ;  
        Image newimg = img.getScaledInstance(lblJezik.getWidth(), lblJezik.getHeight(), Image.SCALE_SMOOTH);
        ikona = new ImageIcon( newimg );
        lblJezik.setIcon(ikona);
    }
}
